Patternslib/Patterns

demo/inject/documentation.md
As it is, the example would make `#content` from the response replace `#content` on the page, plus the other stuff.
I think the point of the example is to show how to replace multiple blocks of content, so I fixed it to make it do what the description says.
=> Fix an example to make it fit the description

src/pat/bumper/bumper.js, src/pat/bumper/documentation.md, tests/specs/pat/bumper.js
@jcbrand I merged the `_updateStatus` and `_updateContainedStatus` functions into one, since the logic should be the same, save for the type of container.
I fixed the tests accordingly, but currently we are only testing that we bump against the top side, none of the other sides.  How do you suggest to structure additional tests?  Technically, it should be a 3D matrix:
(scrolling container/window) x (top/right/bottom/left) x (all/)
That could get unwieldy.
@cornae this fixes #403 and fixes #404.
=> Fixes #403 and #404.

src/pat/date-picker/date-picker.js
Without this, selecting a date does not trigger pat-autosubmit.
=> onSelect: trigger input-change on the parent form

bower.json, package.json, src/pat/modal/modal.js
- when source/target missing error event is raised detach modal
- use already registered name in bower.json otherwise ``bower link`` that is
ment for development cannot be used
- git clone github/ploneintranet.prototype
- make dev-bundle
- make serve
- open browser at http://127.0.0.1:4000/minutes-of-2014-06-09/
- click "Delete this document" button
- without this PR spinner icon is not removed
/cc @pilz
-
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/patternslib/patterns/408)
=> pat-inject/pat-modal spinner bug

src/pat/clone/clone.js, src/pat/selectbox/selectbox.js, src/pat/tooltip/tooltip.js
- when content_html is set as source you can pass any html string and that is going to be used inserted in tooltip.
- added ``data-option-value`` option for pat-selectbox pattern
- fixed IE9-11 bug in pat-clone that was happening with textareas and placeholder
/cc @pilz @cornae
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/patternslib/patterns/410)
=> pat-tooltip: add content_html option for source parameter

src/pat/inject/inject.js
When performing an injection on form submit, the history back doesn't work.
Right after the injection is done, pat-inject puts the config url into the history. 
It gets this config url by looking at the injection url. 
* Either it was explicitly specified as url in the data-pat-inject
* Or it was specified as a formaction on a button
* Or it comes from the href attribute of a link
* Or it comes from an action attribute of the current elem
* Or it comes from an action attribute from a surrounding form element.
However, if this falls back to the action attribute of a form, there is no query string. Imagine the following process on a search form that injects its results on subsequent searches:
* The user uses some sitewide form field to initiate a search by typing “X” as search term
* The …
=> Add information on subform fields on submit so that history can set the right url

src/core/utils.js
Remove unused jquery.browser and underscore dependencies from core/utils.js.
I suspect the ``jquery.browser`` dependency being the cause, why patternslib cannot be built on CMFPlone, where we do not include it.
=> Cleanup core/utils.js dependencies

src/core/parser.js
Shows which argstring throws a parsing error.
Online edit, I don't have a full JS dev stack with tests.
=> more verbose parser warnings

Makefile, src/pat/scroll/debug.html, src/pat/scroll/index.html, src/pat/scroll/scroll.js
This fixes #453 : 2 issues with pat-scroll:
- Offset was calculated as *visible* offset, not taking into account the actual height of an overflowed scrollable, in which part of the dom is not visible.
- There was an assumption that both the trigger link and the target would be contained within the scrollable element. Actually only the target needs to be within the scrollable. This now makes it possible to have working pat-scroll links outside the actual scrollable.
=> 453 scroll calculation

changes.md, src/pat/masonry/masonry.js
Use always instead of done, because this is called always, not only when images are done loading. This makes sure that we get that final call that will set the masonry-ready class.
=> Layout fix

src/pat/masonry/masonry.js
If e.g. a pat-switch changes the amount of space available to or within the masonry, it needs to layout again. Listening to the pat-update event does this.
=> Trigger a relayout when an update event is triggered by pat-switch et al

src/pat/colour-picker/documentation.md
Deletes the reason line from colour-picker documentation.
@jcbrand
=> Changes to documentation.md

src/pat/scroll/debug.html, src/pat/scroll/index.html, src/pat/scroll/scroll.js, src/pat/scroll/scrollcalculation.svg
**edit: the description below is now superseded. See tail of comments **
> 
> **edit** Actually the backward compatibility injection *does* work so no API change!
> 
> The actual calculation is difficult and requires special markup wich is auto-added and also auto-removed again.
> 
> Immediately *within* the scrollable, around all the scrollable content,
> we need a special wrapper div that provides a positioning context
> by being position:relative. Let's call this .inner-scrollable.
> 
> This enables us to measure the scrolling distance between the #target
> and the top of the scrollable, represented by .inner-scrollable.
> We cannot measure directly against the scrollable itself, because if
> the scrollable is scrolled down, there's invisible (overflowed) content
> 'sticking out' …
=> Completely redo the scrolling algorithm.

changes.md, src/pat/gallery/gallery.js, src/pat/gallery/index.html
pat-gallery: add option ``item-selector`` for gallery items, which are added to the gallery.
Defaults to ``a``.
Fixes situations, when gallery items and normal links are mixed within the same container and normal links would open within the gallery lightbox.
=> pat-gallery: add option item-selector

main.js, package.json, src/pat/calendar/calendar.js, src/pat/calendar/moment-timezone-with-data-2010-2020.js, src/pat/date-picker/date-picker.js, src/pat/main.js
This does some cleanup to include moment-timezone with data and removes a duplicated include which otherwise resulted in undefined timezone data. Also this now includes the generic moment-timezone-data in pat-calendar instead of a specific one so that timezone data doesn't get included twice if another pattern also requires moment-timzone.
Overall - besides fixing errors - this cuts about 100k off of a full bundle.
=> Calendar fixes

changes.md, src/pat/scroll/scroll.js
Until now this assumed that a url ends with a slash.
This surfaced when updating jekyll and the default to create pages in directories changed to create pages with .html. That killed the detection of which elements to clear so that all items were always cleared.
=> Pat scroll fix

changes.md, src/pat/scroll/scroll.js
An href can also contain a url left of the hashmark. pat-scroll should only care for the part right of the hashmark
=> Pat scroll enhancement

Makefile, changes.md, src/pat/gallery/gallery.js
- pat-gallery: UX improvements - do not close on scroll or pinch.
- pat-gallery: UX improvements - remove scrollbars when gallery is opened.
=> pat-gallery UX improvements

changes.md, src/pat/masonry/masonry.js
pat-masonry: Initialize masonry just before layouting gets startet, which is after first image has been loaded or at loading has finished.
This avoids overlapping images while they are still being loaded.
=> pat-masonry: initialize just before layouting

changes.md, src/lib/input-change-events.js
This fixes an issues with autosubmit.
If you have a `type="text"` input, "autosubmission" is triggered immediately after you type something in the input, with `type="number"` this happens only after you click somewhere else (at least on the latest chrome).
=> fix input-change-events for <input type="number" />

src/pat/modal/index.html, src/pat/modal/modal.js
This change allows it to configure the behavior of pat-modal which moves the first child of the panel-content into the header. With the windows-style modal boxes going slowly away and the move to mobile style modals, we want to be able to steer that behavior. 
This PR is done to be backwards compatible. So if you don't do anything, all will work like before. If you add the new attribute 'panel-header-content: .custom-header' (or even set it to none for no moving), you can make use of the new functionality.
=> Added an option to select (or omit) the header

changes.md, src/pat/masonry/masonry.js
This patch fixes the layout of nested .pat-masonry elements by calling a `quicklayout` on the children.
=> pat-masonry: fix layout of nested .pat-masonry elements

changes.md, src/pat/modal/modal.js
pat-modal: Only add a panel-header to the first panel-content element within pat-modal, not everyone. Otherwise this may collide with pat-collapsible which also creates a panel-content class further down the DOM (pilz)
=> pat-modal fix to avoid collisions with pat-collapsible

_sass/_patterns.scss, src/pat/checklist/checklist.js, src/pat/selectbox/selectbox.js, src/patterns.js, style/patterns.css
pat-checkedlist is a pattern which was developer induced. It's functionality should be implemented by pat-selectbox and pat-checklist instead. This PR moves relevant code to handle checked classes on labels from checkedflag to checklist.
=> move checked class behaviour to pat-checklist

CHANGES.md, src/pat/tooltip/tooltip.js
On recent chrome versions, if you have tooltip containing a `form.pat-inject`, the form may not be submitted when you submit it clickiing on a `.close-panel` button with the following error:
```
Form submission canceled because the form is not connected
```
This patch prevents the error hiding the tooltip only after the injection is triggered.
Closes ploneintranet/issues#1498
=> Wait for injection to be triggered before closing the tooltip

src/pat/switch/switch.js
This fixes the injection of links with the option `trigger: autoload-visible` inside an hidden element made visible after a pat-switch event.
=> Fix pat-switch

CHANGES.md, src/pat/validation/tests.js, src/pat/validation/validation.js
Currently the validation of date inputs is broken because we need to pass a format and a parser, see:
- https://validatejs.org/#validators-date
=> Fix pat validation

src/pat/checklist/checklist.js
This prevents an error when `_._findSiblings` exits returning undefined.
=> Make code more solid

src/pat/inject/inject.js
Fixes an issue that happens when the autoload visible link is injected in a collapsed element (see #555).
The collapsed element has no scrollbar until it is expanded.
When it is expanded and we scroll down until the link is visible it is already too late: the link will not be injected.
Clicking it was not triggering the injection.
Only resizing the window triggered the injection.
=> Clicking on an autoload visible link should inject properly

CHANGES.md, src/pat/checklist/checklist.js
…ecause of some bugs in sizzle.uniquesort. Upgrading to jQuery 3 would solve this. As an alternative, we can use ES5 Sets to circumvent the problem.
Refs:
- https://bugs.jquery.com/ticket/13331
- https://github.com/jquery/sizzle/issues/191
=> speed up by switching to sets

src/pat/inject/index.html, src/pat/inject/inject.js
This adds support for `delay` on normal click triggers for injection. Note that the timer starts counting from the moment the AJAX call has completed.
=> Support delay on click

src/core/utils.js, src/pat/inject/index.html, src/pat/inject/inject.js, src/pat/tooltip/tooltip.js, tests/specs/core/utils.js
This PR add a utility method to parse time periods. It assumes milliseconds by default (which guarantees backwards compatibility). Supported units are:
* `s`: seconds
* `ms`: milliseconds
* `m`: minutes
This is currently used by the delay option for the injection and tooltip patterns.
=> Support time units

package-lock.json, package.json
@wichert Cornelis reports this is broken since before christmas, but I didnt identify what broke it. 
Submitting a form through injection resulted in the following error
=> bump to 4.2.2 to fix .ajaxSubmit not a fucntion in form injections

src/pat/ajax/ajax.js
It seems this is needed for `quaive.resources.star` compiled bundle to properly initialize the jquery form.
The bundle compiled without this patch was failing in submitting ajax form:
=> Add jquery form to the arguments

src/pat/checklist/checklist.js
IE 11 does not support:
- the spread operator (http://kangax.github.io/compat-table/es6/#test-spread_(...)_operator)
- for item of iterable (http://kangax.github.io/compat-table/es6/#test-for..of_loops)
=> Restore IE11 compatibility

src/pat/checklist/checklist.js
This fixes the checkbox listing selection modified in #584.
Without this patch, clicking any button in a hierarchy of checkboxes would select all the checkboxes.
=> Fix siblings selection

CHANGES.md, src/pat/calendar/calendar.js
This check is meant to make sure that we see all events in case there are no category controls. However, it mistakenly checks for any *selected* categories, not for any *existing* category controls. This means that if there are category controls and they are all deselected then all events are shown. This patch fixes the check.
=> pat-calendar: Check for existing categories, not for selected ones.

webpack/karma.config.js
Now you can run tests and have the browser developer tools actually stop on `debugger;` breakpoints:
> karma start webpack/karma.config.js --browsers PhantomJS_debug
=> Add a "PhantomJS_debug" custom launcher.

CHANGES.md, src/core/parser.js
This looks to me a sane workaround for:
- https://github.com/Patternslib/Patterns/issues/393
Prevents the parser to pollute the pat-modal configuration
with data-pat-inject elements define in a `.pat-modal` parent element.
Probably this function should be completely revisited, see:
- https://github.com/Patternslib/Patterns/issues/627
Fixes #393
Refs #627
=> Fix .pat-modal inside [data-pat-inject]

CHANGES.md, src/pat/scroll/tests.js
Attempt 1: Wait for scrolling to be done.
Also remove imagesloaded, as we do not need to wait for images (was
called incorrectly without a callback anyways).
=> Fix heisenbug with pat-scroll on testruns.

.travis.yml, CHANGES.md, Makefile, _sass/_patterns.scss, index.html, npm-shrinkwrap.json, package.json, src/pat/fullscreen/_fullscreen.scss, src/pat/fullscreen/documentation.md, src/pat/fullscreen/fullscreen.js, src/pat/fullscreen/index.html, src/pat/fullscreen/tests.js, src/pat/scroll/tests.js, src/patterns.js, style/patterns.css, webpack/base.config.js, webpack/karma.config.js
Add ``pat-fullscreen`` pattern to allow any element to be displayed in fullscreen-mode.
=> Add pat-fullscreen pattern

CHANGES.md, src/pat/fullscreen/documentation.md, src/pat/fullscreen/fullscreen-close.js, src/pat/fullscreen/fullscreen.js, src/pat/fullscreen/tests.js, src/patterns.js, webpack/base.config.js
A second pattern ``pat-fullscreen-close`` which is triggered on ``close-fullscreen`` CSS class allows for closing the fullscreen with custom buttons.
=> Add pat-fullscreen support for close

.gitignore, CHANGES.md, README.md, npm-shrinkwrap.json, package.json, webpack/base.config.js
Add webpack visualizer as a backport/cherry-pick from https://github.com/Patternslib/Patterns/pull/672 as we probably want this feature right away to understand the bundle size.
Done as pre-requisite of other bugfixes.
This gives us a stats.html. Open, select bundle.js (otherwise bundle.min.js is just summed up to bundle.js) and analyze. Should look like this:
=> Add webpack visualizer (backport from thet-updates)

CHANGES.md, package.json
yarn refused to install patternslib with a semantic versioning incompatible version scheme.
Try:
```$ node
> const semver = require('semver');
> semver.valid('4.0.0')
'4.0.0'
> semver.valid('4.0.0dev')
null
> semver.valid('4.0.0.dev')
null
> semver.valid('4.0.0-dev')
'4.0.0-dev'
```
=> Fix version scheme to be semver compatible

CHANGES.md, npm-shrinkwrap.json, package.json, src/core/utils.js, src/pat/inject/index.html, src/pat/inject/inject-text.html, src/pat/inject/inject.js, tests/specs/core/utils.js
Fix scrolling behavior - whole page was scrolling when using Element.scrollIntoView().
Add ``utils.getCSSValue`` for retrieving CSS property values for DOM nodes.
Upgrade moment to avoid duplicate dependencies.
=> Fix scrolling behavior, add getCSSValue

src/core/utils.js, src/pat/inject/index.html, src/pat/inject/inject.js, tests/specs/core/utils.js
fix retrieving border value in pat-inject scrolling feature. explicitly test rel-to-abs value and shorthand-to-individual property conversion of getCSSValue
Followup of #694
=> #694 followup: pat-inject scrolling fixes

CHANGES.md, Makefile, _sass/_settings.scss, package-lock.json, src/pat/navigation/index.html, src/pat/navigation/navigation.js, src/pat/navigation/pattern-test-response.html, style/patterns.css
Navigation:
- Do not set the ``.navigation-in-path`` class for elenents already marked with ``.current``.
- Allow configuration of "in path" and "current" classes via ``in-path-class`` and ``current-class`` configuration options.
- Code cleanup.
=> [WIP] Updating navigation pattern

index.html, src/pat/menu/documentation.md, src/pat/menu/index.html, src/pat/menu/menu.css, src/pat/menu/menu.js, src/pat/menu/tests.js
Followup of https://github.com/Patternslib/Patterns/pull/496 from 2017 to reduce open PRs as preparation for the Alpine City Sprint.
Changes from #496 plus:
- Makes menu pattern work.
=> Fix menu pattern

src/pat/depends/depends.js
The class visible or hidden was never set in the on init method. 
To fix I use the hideOrShow utils method in the on init instead of calling the show/hide methods. 
Subsequently we call the updateModal method which was otherwise called in the show/hide methods. these two methods will now no longer be used and therefore removed.
=> Fix initial load for transition: css

CHANGES.md, src/pat/scroll/documentation.md, src/pat/scroll/index.html, src/pat/scroll/scroll.js
Ref: https://github.com/Patternslib/Patterns/issues/721
Note:
IIRC, The original issue appeared when injecting content into a site where we want to scroll to the top of the page and not keep the old scroll position.
This problem is actually widely known - e.g. vue-router has a special `scrollBehavior` option for route-changes for this: https://router.vuejs.org/guide/advanced/scroll-behavior.html
An alternative solution would be to implement the scrolling behavior in pat-inject after the injection was done.
@cornae @pilz
=> pat-scroll: Implement `selector:top`

CHANGES.md, src/core/scroll_detection.js, webpack/base.config.js
- Rework and optimize
- Set scroll classes on any scrolling event
- Fix problem with IE
- Set initial state.
Fixes: https://github.com/Patternslib/Patterns/issues/701
=> scroll detection optimizations

CHANGES.md, src/pat/inject/documentation.md, src/pat/inject/inject.js
- pat-inject: Rename undocumented ``selector`` property to ``defaultSelector``.
- pat-inject: Fix typo in docs for the ``source`` property.
=> pat-inject: default selector

src/pat/scroll/scroll.js
hotfix for #721, PR: #722 
pat-scroll: Implement new special `selector:top` attribute value to scroll the scroll container just to the top of the page.
Ref: #721
Fixes: #721
=> pat-scroll: Implement `selector:top` value.

CHANGES.md, src/core/utils.js, src/pat/inject/inject.js, src/pat/inject/tests.js, tests/specs/core/utils.js
core/utils rebaseURL: Do not rebase if the base URL isn't absolute or doesn't start with an URL scheme.
Note: the method ``_rebaseHTML_via_HTMLParser`` is unused.
I will remove this method and ``lib/htmlparser`` in https://github.com/Patternslib/Patterns/pull/731
=> fix rebaseURL to work only with correct base URLs

CHANGES.md, src/core/utils.js, src/pat/inject/inject.js, tests/specs/core/utils.js
core/utils rebaseURL: Change a relative base url to an absolute URL using window.location.
=> rebaseURL fix take 2

.modernizrrc.js, CHANGES.md, package-lock.json, package.json, src/modernizr-config.json, src/pat/validation/index.html, src/pat/validation/tests.js, src/pat/validation/validation.js
Fixed by checking if input.validity.badInput is true for date/datetime-local fields. If so, check the date, if not, it might have been empty.
Due to the ``ValidityState`` object only being updated after user input and not on programmatic input it cannot be tested.
See the discussion here: https://twitter.com/thetetet/status/1285239806205755393
and here: https://stackoverflow.com/questions/53226031/html-input-validity-not-checked-when-value-is-changed-by-javascript
=> pat-validation: Do not trigger on empty dates. Fixes: #711

CHANGES.md, src/pat/validation/documentation.md, src/pat/validation/index.html, src/pat/validation/tests.js, src/pat/validation/validation.js
This is particularly interesting for password or email confirmation fields
=> pat-validation: Added the possibility to check for fields equality

src/pat/validation/tests.js, src/pat/validation/validation.js
Bugfix for
https://github.com/Patternslib/Patterns/issues/711
https://github.com/Patternslib/Patterns/pull/717
=> Fix broken date before/end constraint validation.

CHANGES.md, src/pat/validation/index.html, src/pat/validation/tests.js, src/pat/validation/validation.js
The HTML5 specs allow for an ``required`` attribute without a value. We're not supporting this in pat-validation until now. This PR fixes this.
Now we can use:
```
<input type="text" name="req1" required="required" />
```
as well as 
```
<input type="text" name="req1" required />
```
See:
https://html.spec.whatwg.org/multipage/input.html#attr-input-required
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required
=> pat-validation: Allow for HTML5 style required attributes without a value

CHANGES.md, src/pat/validation/index.html, src/pat/validation/tests.js, src/pat/validation/validation.js
=> Include hidden input.pat-autosuggest in validation

CHANGES.md, src/pat/tooltip/tooltip.js, src/pat/tooltip/tooltip.test.js
- Restore old behavior of "source: content" where it only uses the triggers content and not another DOM structure.
- Remove "source: auto" (See: https://github.com/quaive/ploneintranet.prototype/issues/859#issuecomment-695997028 )
=> Updates to pat-tooltip

.travis.yml, CHANGES.md, Makefile, README.md, src/pat/calendar/calendar.js, src/pat/carousel/carousel.js, src/pat/depends/depends.js, src/pat/depends/index.html, src/patterns.js, src/public_path.js, webpack/base.config.js
-   Allow overriding the public path from outside via the definition of a ``window.__patternslib_public_path__`` global variable.
Plus other fixes:
-   pat calendar: Fix language loading error "Error: Cannot find module './en.js'"
-   pat depends, pat auto suggest: Fix a problem with initialization of ``pat-auto-suggest`` which occurred after the lazy loading changes. 
-    Cleanup
Lazyloading external modules:
- https://github.com/quaive/ploneintranet/pull/3617
- https://github.com/quaive/quaive.resources.ploneintranet/pull/44
- https://github.com/quaive/ploneintranet.prototype/pull/1085
- https://github.com/Patternslib/Patterns/pull/759
Already merged:
- https://github.com/Patternslib/Patterns/pull/758
=> Allow dynamic setting of publicpath, fix language loading error in pat-calendar.

CHANGES.md, package.json, src/polyfills-loader.js, webpack/base.config.js, webpack/prod.config.js, yarn.lock
This PR injects polyfills for Internet Explorer as script tag via the ``polyfills-loader`` script before the bundle is loaded.
This way we do not have to load the huge polyfills payload for all browsers where we do not need them.
Also, the chunks are minified in production mode.
=> Inject polyfills for IE

src/pat/calendar/calendar.js
- Do not set a language default as it would always override the fallbacks.
- Fix pat-checklist not initializing de/select buttons due to jQuery not listening to raw JavaScript event.
=> pat-calendar: language fix, de/select categories button fix

src/pat/calendar/calendar.js
Cancel scheduled filter runs if another checkbox change triggers the next run.
=> pat calendar: Improve filtering performacne

CHANGES.md, src/core/dom.js, src/core/dom.test.js, src/core/utils.js, src/core/utils.test.js, src/pat/depends/index.html, src/pat/selectbox/documentation.md, src/pat/selectbox/index.html, src/pat/selectbox/selectbox.js, src/pat/selectbox/selectbox.test.js
- pat select: Add missing ``<span>`` element around the select element itself. Fixes: https://github.com/quaive/ploneintranet.prototype/issues/1087
- pat depends: Do not set inline styles when showing elements in transition mode ``none``. Fixes #719.
=> Couple of fixes

CHANGES.md, src/pat/date-picker/date-picker.js, src/pat/date-picker/date-picker.test.js, src/pat/date-picker/documentation.md, src/pat/date-picker/index.html, src/pat/datetime-picker/datetime-picker.js, src/pat/datetime-picker/datetime-picker.test.js, src/pat/validation/index.html
Ready to review.
Works as we discussed it:
When "date input A" depends on "date input B" via the ``after`` argument the following happens:
- If A is unset but B is set, it will be set to B+offset days
- If B > A, A will be set to B+offset days
@pilz - I have the feeling that my wording in the documentation is a bit clumsy. I'd happy for improvements.
See the example in index.html on how to use it.
Special feature: It should work with multiple "after" dependencies - so if the ``after`` selector matches multiple other input fields, it should update for each of them.
When starting this branch with ``make serve`` there are two new inputs at the end of this page, configured with an offset of 2 days:
http://0.0.0.0:3001/src/pat/date-picker/
Also I've updated the pat-validation demo with this …
=> end date should update when changing start date

CHANGES.md, package.json, src/pat/tooltip/index.html, src/pat/tooltip/tooltip.js, src/pat/tooltip/tooltip.test.js, yarn.lock
Ref: https://jira.syslab.com/browse/SCR-660
1)  Introduce new option ``arrow-padding`` to define the padding of the box arrow from the corners of the tooltip.
2) Set content when mounting to avoid positioning problems.
@cornae the second point should fix the problem with the misplaced tooltip when opening the personal menu.
Regarding mentions tooltips in the activities stream comments box, which reaches far below the fold: I want to re-mention the already discussed fix, because I think this one would make the situation better than it is without me adding any functionality.
If we set the following in CSS (or something similar):
```
.tippy-box .tippy-content {
max-height: calc(50vh - 50px);
min-height: 20em;
}
```
We get this result:
You can even restrict it to specific tooltips if, for …
=> Tooltip fixes

CHANGES.md, src/pat/tabs/tabs.js, src/pat/tabs/tabs.test.js, src/setupTests.js
1) Fix classname to "open" and attach it to the ``pat-tabs`` element instead of ``extra-tabs``.
2) Fix to debounce initial tabs adjustment and place it after initialization of the ResizeObserver. This fixes wrong size calculation when pattern is initialized but layout not settled.
Refs:
https://jira.syslab.com/browse/SCR-661
https://github.com/Patternslib/Patterns/issues/752
https://github.com/Patternslib/Patterns/issues/751
https://github.com/quaive/ploneintranet.prototype/issues/1111
https://github.com/quaive/ploneintranet.prototype/issues/1112
=> Scr 661 fixes

CHANGES.md, src/core/registry.js, src/pat/auto-submit/auto-submit.js, src/pat/auto-submit/index.html, src/pat/auto-suggest/auto-suggest.js, src/pat/auto-suggest/auto-suggest.test.js
Fix a problem where pat-auto-suggest wasn't auto-submitting content.
That was due to pat-auto-suggest extending the base pattern since ES6 and that didn't invoke the transform method.
Basic fix in: https://github.com/Patternslib/Patterns/commit/99b8fa0c7aecd00d634402c11b34a029c75bbef0
Other commits and simplifications are byproducts of analyzing the problem.
=> Fix autosuggest autosubmit

src/pat/tabs/tabs.js
Also listen for ``pat-update`` event for cases where no resize but an immediate display of the element is done.
Fixes robots tests failing on opened sidebar menu items hidden behind extra-tabs due to missing CSS transition.
=> Fix issue with pat-tabs not working with disabled transitions

CHANGES.md, src/pat/autofocus/autofocus.js, src/pat/autofocus/autofocus.test.js, src/pat/autofocus/index-iframed.html, src/pat/autofocus/index.html
- Do not autofocus in iframes. Fixes: #761.
Plus:
- Implement documented behavior to not focus on prefilled element, if there is another autofocus element which is empty.
- Instead of calling autofocus for each element call it only once.
- Register event handler only once.
=> Do not autofocus in iframes + other fixes.

src/pat/calendar/calendar.js
Fixes problem with doubling up events when visiting different fullcalendar pages with different urls via pat-inject.
=> pat calendar: Do not modify original event sources config.

.github/workflows/test.yml, CHANGES.md, package.json, src/core/dom.js, src/core/dom.test.js, src/pat/checklist/checklist.js, src/pat/checklist/checklist.test.js, src/pat/checklist/index.html, src/polyfills.js, yarn.lock
- Fixing scope problems,
- Fixing label/fieldset setting problems,
- Fixing problem with global de/select button changing all de/selects.
- Use GitHub Actions.
- Remove Travis CI integration.
=> checklist rework

src/pat/tooltip/documentation.md, src/pat/tooltip/index.html, src/pat/tooltip/tooltip.js, src/pat/tooltip/tooltip.test.js
Remove unannounced (not in changelog) feature which allowed for ::element
modifiers in href references to tooltip content.
Likewise as in pat-inject ::element modifiers selected the element itself with el.outerHTML instead of el.innerHTML.
This was problematic with rebasing URLs in pat-inject.
=> pat-tooltip: Remove ::element modifier for references to tooltip content

CHANGES.md, src/core/dom.js, src/core/dom.test.js, src/core/utils.js, src/pat/inject/documentation.md, src/pat/inject/index.html, src/pat/inject/inject.js, src/pat/inject/inject.test.js, src/pat/inject/test_404.html
Ref: https://github.com/Patternslib/Patterns/issues/735
=> pat-inject - Better Error Reporting on inject

CHANGES.md, src/core/base.js, src/core/dom.js, src/core/dom.test.js, src/core/mockup-parser.js, src/core/parser.js, src/core/registry.js, src/core/utils.js, src/core/utils.test.js, src/pat/auto-submit/auto-submit.js, src/pat/auto-suggest/auto-suggest.js, src/pat/autofocus/autofocus.js, src/pat/bumper/bumper.js, src/pat/calendar/calendar.js, src/pat/calendar/index.html, src/pat/collapsible/collapsible.js, src/pat/collapsible/index.html, src/pat/date-picker/date-picker.js, src/pat/date-picker/index.html, src/pat/datetime-picker/datetime-picker.js, src/pat/inject/index.html, src/pat/inject/inject.js, src/pat/inject/inject.test.js, src/pat/legend/legend.js, src/pat/scroll/scroll.js, src/pat/slides/slides.js
- core parser, core mockup-parser, core base, core registry: modernize code
- code dom: Make find_parents more robust against DocumentFragments with no parent.
- core utils: Add jqToNode to return a DOM node if a jQuery node was passed
- Fix tests: Add missing import for jquery-ext where it's needed.
- pat autofocus: Avoid jQuery extended CSS selector syntax.
- pat slides: Avoid jQuery extended CSS selector syntax.
- __pat inject: Rebase URLs in pattern options.__
=> Rebase URLs in pattern options.

CHANGES.md, src/pat/tooltip/tooltip.js, src/pat/tooltip/tooltip.test.js
pat tooltip: Change show/hide classes to ``tooltip-active-click`` resp. ``tooltip-active-hover`` and ``tooltip-inactive``.
Fixes: https://github.com/quaive/ploneintranet/issues/3723
Ref: https://jira.syslab.com/browse/SCR-838
Ref: https://github.com/quaive/ploneintranet.prototype/issues/1147
=> pat tooltop: Change show/hide classes to less generic names.

CHANGES.md, src/pat/forward/documentation.md, src/pat/forward/forward.js, src/pat/forward/forward.test.js, src/pat/forward/index.html
-   pat forward: Add `delay` option for delaying the click action forwarding for a given number of milliseconds.
-   pat forward: Add `self` as possible value for the `selector` option to trigger the event on itself.
=> pat forward: Add `delay` parameter and `self` for `selector`.

CHANGES.md, src/pat/calendar/calendar.js, src/pat/calendar/calendar.test.js, src/pat/calendar/documentation.md, src/pat/calendar/index.html, src/pat/calendar/test_event.html, src/pat/calendar/test_event_source.json
- Support for rendered events via some configuration options.
Plus:
- Deactivate some more event-add related code paths if not needed.
- Do not include properties not existent in the event source. Avoids problem of setting a href attribute of undefined in the calendar.
Refs:
https://github.com/quaive/ploneintranet.prototype/issues/1184
https://github.com/quaive/ploneintranet.prototype/commit/e51717c0cdc6d95ce8a2222b6453becc0fe65df1
scr-844
=> Support for pat-switch + minor optimizations.

CHANGES.md, src/pat/calendar/calendar.js, src/pat/calendar/calendar.test.js
I noticed a pat-inject loading icon on events without a URL parameter, which then are rendered as `<a>` elements without a `href` - see screenshot.
This PR fixes that - it only sets pat-inject if the event has a url configured.
pat-switch is still active on these elements.
@cornae do you agree with this changed behavior?
Use cases might be where users do not have the rights to view the detail view of an event (like in our absences app).
=> pat-calendar: pat-inject is only set event has a url.

CHANGES.md, src/pat/calendar/calendar.js, src/pat/calendar/calendar.test.js, src/pat/calendar/documentation.md, src/pat/calendar/index.html
pat calendar: Support `pat-tooltip` on events with a URL via `pat-tooltip-source` set to `ajax`.
@cornae I gave this feature a second shot, as we need it for the absences app.
I followed your suggestion in https://github.com/quaive/ploneintranet.prototype/pull/1071#issuecomment-683847959 but implemented currently only `pat-tooltip-source` which can be set to "ajax" as only possible value (content or anything else doesn't make sense I guess...).
I did not implement `pat-tooltip-position-list` or other options yet - I'll see how good the default positioning helps us with our requirement.
@cornae I you need any other options, let me know
=> pat calendar: Support pat-tooltip

CHANGES.md, src/pat/calendar/calendar.js, src/pat/checklist/checklist.js, src/pat/datetime-picker/datetime-picker.js
pat calendar, pat checklist, pat datetime-picker: Dispatch DOM events with bubbling and canceling features enabled, as real DOM events do.
Fixes a problem where calendar categories did not show their initial state correctly.
=> Dispatch DOM events with bubbling, canceling

src/pat/calendar/calendar.js
Commit was made due to no events shown in a calendar without filters
applied.
The real fix is to not include any filtering controls.
The code already supports showing all events when no filtering controls
are available.
Revert "pat-calendar: Do not apply filter, if filter is empty."
This reverts commit 2acb2c7cf8230b58917363412fa6b81cd05e1eed.
=> Revert "Do not apply filter, if filter is empty.", as this leads to unexpected UX.

src/core/registry.js, src/core/registry.test.js, src/core/utils.js, src/core/utils.test.js, src/pat/auto-submit/index.html, src/pat/clone/clone.js, src/pat/clone/clone.test.js, src/pat/clone/index.html, src/pat/date-picker/date-picker.js, src/pat/date-picker/date-picker.test.js, src/pat/date-picker/documentation.md, src/pat/date-picker/index.html, src/pat/datetime-picker/datetime-picker.js, src/pat/datetime-picker/datetime-picker.test.js, src/pat/datetime-picker/documentation.md, src/pat/display-time/display-time.js, src/pat/validation/index.html, src/patterns.js, src/polyfills.js
pat date picker: Change styled behavior so that it can be formatted and localized while still submitting iso values.
Example:
- Example: https://github.com/Patternslib/Patterns/blob/scr-905/src/pat/date-picker/index.html#L109
- Doc in: https://github.com/Patternslib/Patterns/blob/scr-905/src/pat/date-picker/documentation.md
- Formatting options: https://momentjs.com/docs/#/displaying/format/
PRs:
- https://github.com/Patternslib/Patterns/pull/815
- https://github.com/quaive/ploneintranet.prototype/pull/1241
- https://github.com/syslabcom/oira.prototype/pull/246
Ref:
- https://github.com/quaive/ploneintranet.prototype/issues/1205
- https://jira.syslab.com/browse/SCR-905
Looks like so:
@pysailor the standard behavior - when no ``output-format`` is given, is to show ISO dates.
Note, there …
=> date picker: formatted date

src/core/dom.test.js, src/core/parser.js, src/core/parser.test.js, src/pat/calendar/calendar.js, src/pat/calendar/calendar.test.js, src/pat/calendar/documentation.md
- fix(pat calendar): Implement calendar-controls.
- Implement calendar-controls to define the search context for calendar UI elements.
This allows UI elements to be defined outside the .pat-calendar context.
- maint(Tests): Remove left-over log messages.
- fix(core parser): Allow line breaks and spaces before and after pattern arguments.
=> Calendarcontrols fix

src/pat/tabs/tabs.js, src/pat/tabs/tabs.test.js
Note: The tests currently don't cover resizing the browser after first init; e.g. when width increases the `tabs-wrapped` class may need to disappear. I've verified this manually only.
Closes #841
=> pat-tabs: Extra classes to indicate tabs state

src/pat/tabs/tabs.js
fix(pat tabs): Improve calculation of available width by querying the new available width after each recurision where a tab has been moved into the extra-tabs span. The width might change due to an applied padding when the extra-tabs span is added.
=> scr 1152 - fixes 3

src/pat/tabs/tabs.js, src/pat/tabs/tabs.test.js
- fix(pat tabs): Only calculate available space twice: Once initially and then after the extra-tabs span including extra classes have been added. This should stabilize tabs calculation in some cases.
- maint(pat tabs): Test for debounce timeout.
=> Stabilize pat tabs

src/core/parser.js, src/core/parser.test.js, src/pat/inject/index.html, src/pat/inject/inject.js, src/pat/inject/inject.test.js
- maint(pat inject): Fix invalid HTML in demo.
- feat(core parser): Add config to not group parsed options. This allows more flexibility when reusing the parser.
-  fix(pat inject): Use the main argument parser when rebasing HTML so that it supports all kinds of arguments, including multiple configurations as seen in pat-inject and semicolons at the end of a config line after a line-break.
=> Fix inject parameter error

src/core/dom.js, src/core/dom.test.js, src/pat/calendar/calendar.js, src/pat/calendar/calendar.test.js, src/pat/display-time/display-time.js, src/pat/display-time/display-time.test.js
Byproduct in working in scr-1389.
With the new method ``acquire_attribute`` we can e.g. get a context-specific language attribute within the DOM tree instead of just using the language form the HTML top element.
- feat(core dom): Add acquire_attribute to get the value of the first occurrence of a defined attribute up the DOM tree.
- feat(core dom): Add parameter to acquire_attribute to return a list of all found attributes up the DOM tree.
=> feat(core): acquire_attribute

src/pat/calendar/calendar.js, src/pat/calendar/calendar.test.js, src/pat/calendar/documentation.md, src/pat/calendar/index.html, src/pat/calendar/test_event_source.json
Possible values: `12h`, `24h`; default: `24h`. See quaive/ploneintranet#3658
Closes #915
=> New format-time parameter

src/pat/inject/inject.js
Attempt to fix https://github.com/Patternslib/Patterns/issues/939
Alternative approach: https://github.com/Patternslib/Patterns/pull/941
=> pat-inject autoload visible: check if element is in viewport to not load elements outside of it.

src/core/events.test.js, src/pat/auto-submit/auto-submit.js, src/pat/auto-submit/auto-submit.test.js, src/pat/auto-suggest/auto-suggest.js, src/pat/auto-suggest/auto-suggest.test.js
Fix a Problem where changes to pat-autosuggest did not invoke a form submission via pat-autosubmit, introduced in Patternslib 7.0.0
=> Fix auto suggest submit

src/pat/tabs/tabs.test.js, src/pat/validation/validation.js, src/pat/validation/validation.test.js
Fixes: https://github.com/Patternslib/Patterns/issues/970
=> pat validation: also check depending date

src/core/registry.js, src/core/registry.test.js, src/pat/clone/clone.js, src/pat/clone/clone.test.js, src/pat/clone/documentation.md, src/pat/legend/legend.js
To disable patterns when scanning markup for patterns, use the ``disable-patterns`` CSS class.
Previously we did use the ``dont-touch-this`` class.
This is deprecated due to a ambiguous name and will be removed in the next major version.
=> feat: Introduce ``disable-patterns`` class to prevent from initializing.

src/pat/scroll-box/documentation.md, src/pat/scroll-box/index.html, src/pat/scroll-box/scroll-box.js, src/pat/scroll-box/scroll-box.test.js
Fixes: https://github.com/syslabcom/zegg-public-website/issues/22
=> Fix scroll box elastic scrolling

src/pat/tooltip/tooltip.js, src/pat/tooltip/tooltip.test.js
The problem with misaligned tooltip arrows due to the remote content not yet fully loaded might have been around since Patternslib 7.12.0: https://github.com/Patternslib/Patterns/releases/tag/7.12.0
This is fixed now.
=> fix(pat tooltip): Fix problem with misaligned tooltip arrow with remote content.

src/core/utils.js, src/core/utils.test.js, src/pat/display-time/display-time.js, src/pat/display-time/display-time.test.js, src/pat/display-time/documentation.md, src/pat/display-time/index.html
Ref: scrum-465
implemented: https://stackoverflow.com/a/50157224
this uses a mixture of momentjs and intl. intl can translate "today", "yesterday" and "tomorrow" - momentjs does not have these translations available. MomentJS‌ can do a "Tuesday" for next tuesday while the Intl relativetimeformat only shows "in x days".
there is yet no solution for "last tuesday"‌ if the formatted date is within a week-range.
momentjs only has translations for "last tuesday at XX o' clock", so it includes the time component (``lastWeek``).
intl does only "x days ago".
but we probably can live with this restriction.
We could of course switch to Intl only, but we would loose the formatting option "Tuesday" for the next tuesday.
If we need more granular formatting options for relative dates, we'd need to …
=> dont include the time in relative formatting if the  original date is a date-only and not a date-time object.

src/pat/auto-submit/auto-submit.js, src/pat/auto-submit/auto-submit.test.js, src/pat/auto-submit/index.html, src/pat/sortable/sortable.js, src/pat/sortable/sortable.test.js
- feat(pat sortable): Trigger pat-update after sorting changes.
Other patterns can react on that for example submitting the form with pat-auto-submit.
- fix(pat auto submit): Support pat-clone and pat-sortable.
When pat-clone adds an element, initialize that element to listen for changes.
When pat-clone removes an element or pat-sortable changes the order, submit the form.
=> pat-auto-submit supping pat-clone and pat-sortable

src/pat/navigation/documentation.md, src/pat/navigation/index.html, src/pat/navigation/navigation.js, src/pat/navigation/navigation.test.js
feat(pat navigation): Add URL-based navigation markers.
That feature was also present in the old implementation but is now improved.
feat(pat navigation): When a navigation wrapper is in-path, also mark the corresponding anchor as in-path.
maint(pat navigation): Refactor implementation for more stability.
maint(pat navigation): Modernize code.
maint(pat inject): Move core.utils.rebaseURL to inject patterns.
core.utils.rebaseURL was only used by the inject pattern and is in this form not useful for broader use.
If you need to rebase an relative or absolute URL against a base url, use:
new URL(url, base_url)
fix(core base): Do not break when initialized with no element.
maint(core dom): Code optimization for dom.find_parents.
maint(core dom): Update documentation.
maint: Modernize header …
=> Stabilize and extend pat-navigation incl. URL‌ based markings

src/index.js, webpack/webpack.config.js
Since the module federation support jQuery was registered globally too late for some scripts. Now jQuery is registered as soon as the index.js is loaded. This allows for following scripts to use jQuery.
=> fix(Build): Register jQuery globally.

src/core/base.test.js, src/pat/navigation/navigation.js, src/pat/navigation/navigation.test.js
This PR removes the mutation observer.
Since we're almost always using pat-inject for replacing or adding DOM nodes and we already have support for pat-inject, the mutation observer is not necessary.
Removing it improves the performance in situations where the navigation structure is updated - for example off-canvas navigation updates with pat-tabs would invoke many mutation observer callback hits. The previous performance improvement solved the performance penalty by deferring the callback for 10ms, but this is taking that further by avoiding it at all.
=> pat-navigation: Remove mutation observer

src/pat/navigation/navigation.js, src/pat/navigation/navigation.test.js
After a pat-inject has updated the navigation, re-mark all navigation items. This is an alternative and approach to the previous mutation observer based one.
=> feat(pat navigation): Mark the navigation items after injection.

src/pat/tooltip/index.html, src/pat/tooltip/tooltip.js, src/pat/tooltip/tooltip.test.js
The tooltip element's title attribute is only stripped if the source is set to title (the default) and kept otherwise.
Fixes: https://github.com/Patternslib/Patterns/issues/945
=> feat(pat tooltip): Keep the title attribute for source ajax and content.

src/pat/forward/forward.js, src/pat/forward/forward.test.js
When a pat-forward element is clicked, allow to propagate the click event so that other handlers can also react.
Fixes: https://github.com/Patternslib/Patterns/issues/1063
=> feat(pat forward): Do not steal the click event.

src/core/dom.js, src/core/dom.test.js, src/pat/auto-suggest/auto-suggest.test.js, src/pat/date-picker/date-picker.test.js
In Chrome and Safari hidden but required input fields (e.g. hidden automatically by pat-autosuggest or pat-date-picker) cannot be submitted if they fail the browser's native validation. The browser tries to set a validation message but fails because the element is not focusable.
See: https://stackoverflow.com/a/28340579/1337474
=> fix(core dom): show/hide - do not set the hidden attribute.

src/core/utils.js, src/patterns.js
Some smaller improvements from an branch where pat-clone, pat-markdown and pat-syntax-highlight are prepared for self-documenting pattern demos.
=> Improvements from modernize markdown

src/core/basepattern.js, src/core/basepattern.md, src/core/basepattern.test.js
This change is backwards compatible Change the parser attribute to a static attribute and provide it also on the object. This change was necessary because pat-inject was using the parser on a registered Pattern class to rebase URL configurations in the rebaseHTML method. There was no access to the parser attribute on non-instatiated objects before, now it is.
=> feat(core basepattern): Provide the parser as static attribute.

src/pat/bumper/_bumper.scss, src/pat/bumper/bumper.js, src/pat/bumper/bumper.test.js, src/pat/bumper/index.html
Fix pat-bumper regressions by basically re-implementing the bumper logic.
The bumping classes are now set correctly on any bumping direction.
The logic is adapted to work with any top, right, bottom, left, margin, border
and padding setting on a wrapping container, two different containers for x and
y scrolling and on the window viewport as container.
Fixes: https://github.com/Patternslib/Patterns/issues/1083
=> Pat bumper regressions

src/core/utils.js, src/core/utils.test.js, src/pat/auto-submit/auto-submit.js, src/pat/auto-submit/auto-submit.test.js, src/pat/auto-suggest/auto-suggest.js, src/pat/autofocus/autofocus.js, src/pat/autofocus/autofocus.test.js, src/pat/autofocus/index.html, src/pat/bumper/bumper.test.js, src/pat/clone/clone.js, src/pat/clone/clone.test.js, src/pat/collapsible/collapsible.js, src/pat/collapsible/collapsible.test.js, src/pat/depends/depends.js, src/pat/depends/depends.test.js, src/pat/equaliser/equaliser.js, src/pat/equaliser/equaliser.test.js, src/pat/scroll-box/scroll-box.test.js, src/pat/scroll/scroll.js, src/pat/scroll/scroll.test.js, src/pat/sortable/sortable.js, src/pat/sortable/sortable.test.js, src/pat/stacks/stacks.js, src/pat/stacks/stacks.test.js, src/pat/switch/switch.js, src/pat/switch/switch.test.js, src/pat/toggle/toggle.js, src/pat/toggle/toggle.test.js
Fix pat-autofocus regressions by using the pat-update event for re-initializing the pattern after dom changes.
That led to unifying the pat-update event handling all over Patternslib.
=> Pat autofocus regressions

src/core/basepattern.js, src/core/dom.js, src/core/dom.test.js, src/pat/markdown/markdown.js, src/pat/markdown/markdown.test.js, src/pat/stacks/stacks.js, src/pat/syntax-highlight/syntax-highlight.js, src/pat/tooltip/tooltip.js, src/pat/tooltip/tooltip.test.js
Basically this PR fixes a problem where including e.g. pat-tiptap which depends on pat-tootip also includes pat-markdown and pat-syntax-highlight with all the language definitions. This makes the generated bundle huge and creates a suboptimal situation for module federation bundles. Because I want to add the generated bundles to npm packages directly, so that they can be used via unpkg or jsdelivr CDN services. Therefore I'd like to have small bundles and not upload dozens of MB to npm and pollute node_modules directories unnecessarily.
Note: what is not used is not downloaded, so this PR solves not a runtime problem. Except for this one commit except for the one commit where:
Loading of pat-syntax-highlight is optimized - before all languages were bundled into the highlight.js chunk, now …
=> Bundle generation optimizations

yarn.lock
Fix tiptap "Unhandled Promise Rejection" error due to multiple versions of a tiptap dependency installed. Removing yarn.lock in re-installing solves this.
=> fix(Build): Fix tiptap error.

src/pat/checklist/checklist.js, src/pat/checklist/checklist.test.js, src/pat/checklist/documentation.md, src/pat/checklist/index.html
I need a checkbox (for example at the header column of a table) to select/deselect all sibling checkboxes.
This extends the `pat-checklist` pattern to look for a `<input class="toggle-all" />` which selects/deselets all its siblings according to its checked state.
=> Feature: input checkbox to toggle checked boxes true/false.

src/core/dom.js, src/pat/scroll-marker/scroll-marker.js, src/pat/scroll-marker/scroll-marker.test.js
The scroll container was potentially wrong and is a parent of the
hash-link target contents and not a parent of the navigation where
pat-scroll-container (or pat-navigation) are defined upon.
=> fix(pat scroll-marker): Use the correct scroll container

src/pat/navigation/navigation.js
The links within a pat-navigation structure might have child elements, e.g. a span within an anchor. In that case the click target is the span and not the anchor. Apply a fix where a closest anchor of the click target is searched, which might be the click target itself.
=> fix(pat navigation): Fix current marker anchors with child elements.

src/pat/inject/inject.js, src/pat/inject/inject.test.js
- fix(pat inject): Fix a JS error with pat-inject where the scrolling target could not be found.
- fix(pat inject): Allow to use a scroll container other than the injection target.
This fixes a problem when the content should scroll to an element which is within a scroll container below the injection target. Until now the scroll container could only be a parent of the injection
target. Now it can be a parent of the scroll-target.
=> pat-inject scroll fix

src/pat/display-time/display-time.js, src/pat/display-time/display-time.test.js
Default to formatted output according to the current locale. This fixes a regression since 4.1.0 which came with the date picker's styled behavior but let display time output an ISO date instead of a formatted date when not output format was set.
=> fix(pat display time): Default to locale-formatted output.

src/pat/validation/validation.js, src/pat/validation/validation.test.js
Do not disable input elements with the `formnovalidate` attribute set when form validation fails.
E.g. a cancel button: `<button formnovalidate>Cancel</button>`.
Fixes #1132.
=> fix(pat validation): Do not disable input elements with formnovalidate.

src/pat/collapsible/collapsible.js, src/pat/scroll/scroll.js
The scrolling offset was incorrectly calculated since Patternslib
9.9.0-alpha.5. Fix the calculation for the scrolling position by using
`offsetTop` and `offsetLeft` instead `getBoundingClientRect`.
=> Fix scroll to position.

src/pat/inject/inject.js
The original problem fixed in commit 911b8b8660197d44291c7d5a9537bbb496df1a38 for 9.9.0-beta.1 addressed a problem where the scroll target was not a direct child of the injected content but some levels deeper. But this fix broke the situation where the scroll target is a direct child of the injected content. The fix applied here handles both situations.
=> fix(pat inject): Second attempt to fix the scrolling behavior, where the scrolling target could not be found.

package.json, yarn.lock
This fixes a missing build in npm releases.
Now you can again use jsdelivr and unpkg.
=> maint: Upgrade to @patternslib/dev 3.3.3

src/core/parser.js, src/pat/ajax/ajax.js, src/pat/ajax/ajax.test.js, src/pat/inject/inject.js, src/pat/inject/inject.test.js
Fixes a problem recently reported by @cornae
- Submitting `pat-inject` enabled forms without an `action` attribute but a submit button with a `formaction` attribute would break `pat-ajax`.
This fixes also two other problems I found on the way:
- Submitting with a formaction-button called a pat-ajax method twice.
- pat-inject did not support submit buttons without an explicit `type="submit"` attribute, e.g. `<button>`, which is implicitly a submit button.
=> Submit button fixes

src/core/dom.js, src/core/dom.test.js, src/pat/collapsible/documentation.md, src/pat/scroll/scroll.js, src/pat/scroll/scroll.test.js, src/pat/stacks/documentation.md, src/pat/stacks/stacks.js, src/pat/stacks/stacks.test.js, src/setup-tests.js
=> Fix for "unwanted scrolling when inside collapsible"

src/core/events.js, src/core/events.test.js, src/core/utils.js, src/core/utils.test.js, src/pat/checklist/checklist.js, src/pat/checklist/index.html, src/pat/switch/documentation.md
- Fixes performance problems with pat-checklist,
- Fix remove_event_handler logic which wasn't working properly,
- Allow to use wildcard-removal of registered events.
The remove_event_handler fixes and features are hanging around since August.
They are well tested and now even useful for the checklist destroy method within the checklist performance fixes in PR too.
=> Fix performance problems with pat-checklist

src/pat/inject/inject.js, src/pat/inject/inject.test.js, src/pat/modal/modal.js, src/pat/modal/modal.test.js, src/pat/navigation/navigation.test.js, src/pat/sortable/sortable.test.js
See: https://github.com/syslabcom/quaive.prototype/issues/167
=> pat-inject and pat-validation problem.

src/core/events.js, src/core/events.test.js, src/pat/auto-submit/auto-submit.js, src/pat/auto-submit/auto-submit.test.js, src/pat/auto-submit/index.html
One important fix:
- fix(pat-inject): Fix problem with pat-autosubmit together with pat-sortable and/or pat-clone.
And some other minor ones:
- feat(core events): Add a event factory for a generic bubbling and cancelable event.
- maint(pat-autosubmit): Simplify the sortable+clone demo example a bit.
- maint(pat-autosubmit): Add a test for delayed autosubmit.
- maint(pat-autosubmit): Make use of add_event_listener. This has advantages regarding preventing double registrations and allowing wildcard removal.
- Minor code optimization in pat-autosubmit.
=> Various pat-autosubmit fixes and improvements.

src/pat/ajax/ajax.js, src/pat/inject/inject.js, src/pat/inject/inject.test.js
feat(pat inject): Support submit buttons with child elements.
Send the value of a submit button even if a child element of the submit
button was clicked and not the submit button itself.
**Note:** This is not a fix for a regression, but a fix for a problem I found while working on: https://github.com/Patternslib/Patterns/pull/1186
Also, this improves support for form elements outside the form, connected via the input element's `form` attribute. But the current state of this support is yet unknown.
=> Scrum 1670  inject submit child element

src/core/events.js, src/core/events.test.js, src/lib/input-change-events.js, src/pat/auto-submit/auto-submit.js, src/pat/inject/inject.test.js
=> pat inject fixes

src/core/dom.js, src/core/dom.test.js, src/pat/auto-submit/auto-submit.js, src/pat/auto-submit/auto-submit.test.js, src/pat/auto-suggest/auto-suggest.test.js, src/pat/inject/inject.js
There are cases where pat-autosubmit is defined on non-form elements, like:
```
<form>
<div class="pat-autosubmit">
<input>
</div>
</form>
```
pat-autosubmit invoked a submit event but that never reached the form because that follows not the standard and submit events are meant to be invoked on form elements (or maybe inputs, which did work I can't derive that behavior from the specs).
See:
https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#submitevent
This use case was broken since Patternslib 9.9.7 where we switched to JavaScript submit events from jQuery submit events to fix another problem.
Now the submit event is always invoked on the related form element. Actually the input element where a change …
=> Fix auto submit on non-form elements

src/pat/colour-picker/_colour-picker.scss, src/pat/date-picker/_date-picker.scss
Since latest scss build tools which became available in `@patternslib/dev` version 3.6 references to `node_modules` need to be left out. The build tool searches in node_modules anyways. This is now fixed.
=> fix: Fix reference to 3rd party styles in stylesheets.

src/pat/inject/inject.js, src/pat/inject/inject.test.js
Respect the form[novalidate] and button[formnovalidate] attributes and allow the submission of invalid forms.
This is necessary if a cancel button is a submit button and needs to be allowed to submit even if the form input is invalid.
Note: there is one skipped test due to lack of `formnovalidate` support in jsDOM. However, I have tested it manually on a testing page. The fix seems to work in Firefox.
TODO:
=> fix(pat-inject): Allow to submit invalid forms when form/novalidate.

src/pat/date-picker/date-picker.js, src/pat/date-picker/date-picker.test.js
Ref: scrum-2726
This implementation uses good ol' `store` module from `@patternslib/patternslib/src/core/store` - it's still handy.
However, we can spare us the `supported` query because the web storage is just supported in practice by all modern browsers since Firefox 2 etc.
Testing FTW, I found a case where a unsuccessful call to an i18n URL led to an error.
NOTE: in a real environment where multiple instances are
initialized at once on the same page, before the ajax call has
been completed, each instance will do an AJAX call. After that,
when navigating to other pages with other date picker instance
the cached value should be used and no more AJAX calls should be
made.
It would be hard to work around this limitation and I think it's a tradeoff we can live with, right?
=> feat(pat-date-picker): Cache the ajax call to retrieve i18n picker translations.

src/pat/inject/inject.js
Note: This fixes a problem with Mockup injections of pat-structure.
Rework the html rebasing to fix up relative URLs in pat-inject for a simpler and slightly more efficient method to walk over all attributes which need rebasing.
The old method could destroy complex JSON based pattern options, like those from pat-structure in Mockup.
Note: Only one rebase attribute per tag is currently possible. 1) This
is the same as before. 2) We don't need more.
=> fix(pat-inject): Fix pat-inject to not break complex JSON pattern options.

src/core/dom.js, src/core/dom.test.js, src/pat/inject/inject.js
Replaces pat-inject parts from:
- https://github.com/Patternslib/Patterns/pull/943
- https://github.com/Patternslib/Patterns/pull/1023
- https://github.com/Patternslib/Patterns/pull/1069
- https://github.com/Patternslib/Patterns/pull/1161
=> pat-inject code optimizations

src/core/registry.js
Reduce the number of DOM search tests while not changing the behavior.
Less rules means more speed.
=> maint(core registry): Simplify pattern scanning filter.

src/pat/inject/inject.js, src/pat/inject/inject.test.js
=> fix inject with non-existing sources, add tests for title insertion

src/pat/depends/depends.js, src/pat/depends/depends.test.js
This is a better and more standard compliant combination than listening on input and keyup events. This fixes a problem where a pat-autosuggest selection field didn't provoke a change in a pat-depends dependent element.
=> fix(pat-depends): Listen and dispatch input instead of change events.

src/core/feature-detection.js, src/core/logging.js, src/core/registry.js, src/core/registry.test.js
1) fix(core feature-detection): Fix loading of modernizr script.
In some situations loading of the modernizr.min.js script failed because the base url could be incorrect. That is fixed with a non-IE compatible method of getting the current's script URL, which is safe to use. The problem surfaced in Plone while loading the Patternslib library and in between the protect.js script was loaded. The base url was calculated for the protect.js script and the modernizr script could not be loaded.
2)‌ maint(core log): Console.debug is not deprecated. Just use it.
3) fix(core registry): Do nothing with Patterns without a trigger.
Patterns without a trigger broke the registry scan method. Now they don't.
=> fix(core feature-detection): Fix loading of modernizr script.

src/core/dom.js, src/core/dom.test.js, src/pat/depends/depends.js, src/pat/depends/depends.test.js, src/pat/depends/index.html
[feat(core dom): Add method is_button.](https://github.com/Patternslib/Patterns/commit/132e42bbb84784f1ab7cd3e897c90ed5e368c666)
dom.is_button tests, if an element is a button like element.
Button like elements are the following:
button,
button[type=button],
button[type=submit],
input[type=image],
input[type=button],
input[type=reset],
input[type=submit]
[fix(pat-depends): Fix infinite loop situations.](https://github.com/Patternslib/Patterns/commit/af5ecc55b7a9c9fd6a01f0d3ca717d26cbd37ff7)
Fix some situations where infinite loops were created of unnecessary
function calls were done:
- Do not en/disable already en/disabled inputs.
- Do not trigger and pat-depends element if the input is the element
itself and not a contained sub-input.
- Do not trigger input events on button-like …
=> Fix pat depends

src/core/feature-detection.js, src/index.js
Modernizr will be removed in an upcoming minor version. It is not really necessary anymore. Most browser support almost latest web technology and IE is dead.
A no-js class on the body will still be replaced with a js class.
=> maint: Add deprecation notice for Modernizr.

src/pat/checklist/checklist.js
pat-depends was not reacting on pat-checklist toggles. This is fixed by dispatching an input event just after the change event.
=> fix(pat-checklist): Dispatch input event along change event.

src/pat/inject/inject.js, src/pat/inject/inject.test.js
Daniel reported a problem on signal concerning table-row injections. At one point in the current release cycle I had to add a temporary wrapper element to be able to load a string and treat it as a DOM element so that javascript functions can be used to identify elements.
I used a DIV. 
However tr elements cannot be added to divs, therefore the table-row injection failed.
A `<tr>` can live within a `<template>`. Changing the temporary div to a template solves the issue.
This temporary wrapper never makes it into the page, instead is only needed to transform an HTML string to a DOM node, so that we can do DOM operations, like `querySelectorAll` on it. That is used to find all images within the to-be-injected source and attach an event handler on it. 
After that operation, the tag is …
=> fix(pat-inject): Fix problem with inserting table rows.

src/core/polyfills.js, src/core/polyfills.test.js
Note: Not used in Patternslib yet.
=> Add polyfill for navigation API.

src/pat/ajax/ajax.js
This allows to use the URL in an event handler for certain actions.
=> feat(pat-ajax): Pass the URL to the pat-ajax-success event payload.

src/core/basepattern.js, src/core/basepattern.test.js, src/core/events.js, src/core/events.test.js, src/pat/validation/validation.js, src/pat/validation/validation.test.js
https://github.com/Patternslib/Patterns/pull/1245
https://github.com/plone/mockup/pull/1455
https://github.com/plone/plonetheme.barceloneta/pull/398
=> introduce pat-update event factory, use it in basepattern, emit after validation checks.

src/pat/validation/documentation.md, src/pat/validation/validation.js, src/pat/validation/validation.test.js
=> Validation maintainence
