Patternslib/Patterns

demo/inject/index.html, src/pat/inject.js, tests/specs/pat/inject.js
=> Inject with formaction - completes #389

src/pat/calendar/_calendar.scss
This allows us to bundle the fullcalendar css.
=> pat-calendar: import _fullcalendar.scss

src/pat/gallery/gallery.js, src/pat/inject/inject.js, src/pat/validate/validate.js
- pat-validate: skip validation when button has a class validate-ignore
- pat-gallery: dont require gallery pattern to be limited to img elements
- pat-inject: when injecting check and ask if target is dirty
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/patternslib/patterns/411)
=> multiple fixes

src/pat/inject/inject.js, src/pat/tooltip/documentation.md, src/pat/tooltip/tooltip.js
i would love to get some comments what i'm doing is in line with patternslib plans.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/patternslib/patterns/413)
=> tooltip and inject changes

src/pat/inject/inject.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/patternslib/patterns/414)
=> pat-inject: listen for 'click.pat-inject' event in all other cases

src/pat/expandable-tree/documentation.md
This prevents the loading spinner from spinning perpetually..
=> add empty documentation section

RELEASE.md, VERSION.txt, build.js
add version.md file, prepend version number to bundle.js when creating a bundle, update release instructions.
=> improved versioning process

src/pat/bumper/bumper.js
Some code styling cleanup in the commit obscures the solution in the diff.
The line that fixes things is:
frame = bumper._getBoundingBox($container, 0);
=> Pat bumper margin issue fix

src/core/utils.js, src/pat/bumper/bumper.js, src/pat/scroll/scroll.js
Pat scroll - add current class to active anchors and their targets.
=> Pat scroll add current class to active anchors..

src/pat/clone/documentation.md
you mean add rather than remove
=> Correct documentation for pat-clone

index.html
This corrects the link to the Notifications demo in the demo html file.
=> Correct Link in demo index.html

src/pat/colour-picker/colour-picker.css, src/pat/colour-picker/colour-picker.js, src/pat/colour-picker/documentation.md, src/pat/colour-picker/index.html
I would like any suggestions. I would also like, if there is, a reason for choosing Spectrum to base colour-picker upon.
=> Documentation for colour-picker

src/pat/auto-scale/auto-scale.js
And look for the wrappers parent for dimensions. This allows adaption on resize.
=> Dont duplicate wrapper

src/pat/ajax/ajax.js
When using pat-inject with pat-autosubmit, it is possible that subsequent ajax requests are terminated by the first one succeeding. This PR keeps track of all issued ajax requests per url and only executes the last one.
See https://github.com/quaive/ploneintranet.prototype/issues/398 for more in depth details.
=> keep counter of initialised requests by url

src/pat/calendar/calendar.js
Pick PR basically "cherry picks" this commit https://github.com/Patternslib/pat-calendar/commit/4c8055cc9cc08f8d20fef2aee749cb1b82d6a3b0 by @jcbrand
=> Do not redraw calendar when the action happens in the tooltip

src/pat/menu/index.html, src/pat/menu/menu.css
I've added a very simple demo for the menu pattern, which basically just changes colors and font-size with the classes `closed` and `open`.
=> Add demo for menu Pattern

src/pat/modal/modal.js
Also allow close buttons which don't inject to close again
=> Chrome modal fix 2

.editorconfig
This tries to provide a consistent styling for the files in this repository.
The values set in the editorconfig file are taken analyzing some sample files.
=> More editorconfig rules

CHANGES.md
This is the missing changelog for #539
=> Added a changelog line

package-lock.json, src/pat/auto-scale/auto-scale.js
Wrongly the test whether we should wrap or not assumed that there is always a class attribute on the parent when checking whether we are already wrapped. That of course is not always necessarily true.
=> fix not-wrapping in case parent has no class

CHANGES.md, package-lock.json, src/core/utils.js, src/pat/scroll/tests.js, tests/specs/core/utils.js
Cornelis found while retouching patternslib.com that data urls get rebased with a / on inject. This excludes data: urls from rebasing.
=> Test if a src is a data: url and don't touch it

CHANGES.md, src/pat/inject/index.html, src/pat/inject/inject.js
This PR extends the injection pattern to support an idle trigger.
This fixes curvetips/customer-site-prototype#9
=> Idle trigger for injection

CHANGES.md, src/modernizr.js, src/pat/checklist/checklist.js
Reverts Patternslib/Patterns#562
This is not complete yet
=> Revert "Using a jquery array with larger lists (above 10) in chrome is slow b…"

CHANGES.md, src/pat/checked-flag/checked-flag.js
=> Replicate PR #564 for pat-checked-flag

src/pat/equaliser/equaliser.js, src/pat/equaliser/index.html, src/pat/masonry/index.html, src/pat/masonry/masonry.js
Don't merge yet, this is a request for comment for now.
Attempt to implement Wichert's suggestion of mutation observers. I am looking for hints of what side effects I might have missed and might need to take into account.
We also discussed to make masonry rendering less expensive by storing if we need to recalculate at all. That is not in here yet.
=> Mutationobserver masonry

package-lock.json, src/pat/bumper/tests.js, src/pat/masonry/tests.js, src/pat/scroll/tests.js, src/pat/tooltip/tests.js
Should fix most of the ie11 test failures
=> fixing ie11 test failures

src/core/jquery-ext.js
ref https://github.com/plone/plone.patternslib/pull/26
=> Backport a fix submitted by kcleong for plone.patternslib

CHANGES.md, package.json
when running tests locally on master via ``make check`` i get the following error:
```
TypeError: Cannot read property 'compilation' of undefined
at WrapperPlugin.apply (/home/_thet/data/dev/plone/patternslib/Patterns/node_modules/wrapper-webpack-plugin/wrapper-webpack-plugin.js:22:18)
at Compiler.apply (/home/_thet/data/dev/plone/patternslib/Patterns/node_modules/tapable/lib/Tapable.js:375:16)
at webpack (/home/_thet/data/dev/plone/patternslib/Patterns/node_modules/webpack/lib/webpack.js:33:19)
at Plugin (/home/_thet/data/dev/plone/patternslib/Patterns/node_modules/karma-webpack/lib/karma-webpack.js:67:16)
at invoke (/home/_thet/data/dev/plone/patternslib/Patterns/node_modules/di/lib/injector.js:75:15)
at Array.instantiate (/home/_thet/data/dev/plone/patternslib/Patterns/node_modules/di/l …
```
=> test if tests run green.

package-lock.json, package.json, src/pat/date-picker/_date-picker.scss, style/patterns.css
=> Fix file path

package-lock.json, src/pat/inject/index.html, src/pat/inject/inject.js, style/patterns.css
This PR adds code to the error handler that takes the error and puts it into a notification at the end of the body. 
This is just a proof of concept for @cornae to validate.
=> demo how we could show inject errors

CHANGES.md, src/pat/modal/modal.js
=> Remove an handler after the modal is closed

CHANGES.md, package-lock.json, src/pat/notification/notification.js, style/patterns.css
=> Fix pat notification

CHANGES.md, package-lock.json, src/pat/date-picker/date-picker.js, src/pat/date-picker/documentation.md, src/pat/date-picker/index.html, src/pat/date-picker/tests.js, src/pat/datetime-picker/datetime-picker.js, src/pat/datetime-picker/documentation.md, src/pat/datetime-picker/index.html, src/pat/datetime-picker/tests.js
Make pat-date-picker and pat-datetime-picker support the firstDay
parameter
Fixes #647
=> Support the `first-day` parameter

src/core/parser.js
=> Optimize the argParserParse function

CHANGES.md, src/pat/modal/index.html
Modal: Add example on how to open a modal on a button via a proxy anchor element.
When reviewing: this is the actual change without the html reformatting:
https://github.com/Patternslib/Patterns/pull/710/commits/08458e264e4a14114559029caaca4955c6064003
Obsoletes: https://github.com/Patternslib/Patterns/pull/709
=> Example: open modal on button via anchor

CHANGES.md, src/pat/scroll/scroll.js
pat-scroll: To define the scrollable target search also for overflow-x and overflow-y declarations.
=> pat-scroll: Fix autoscroll with overflow-x/y

CHANGES.md, index.html, src/pat/push/documentation.md, src/pat/push/index-push-content.html, src/pat/push/index.html, src/pat/push/push.js, src/pat/push/tools/.gitignore, src/pat/push/tools/README.md, src/pat/push/tools/initpython.sh, src/pat/push/tools/rabbitmq_enabled_plugins, src/pat/push/tools/rabbitmq_start.sh, src/pat/push/tools/send.py, src/patterns.js, webpack/base.config.js
ready for review.
There are some instructions on how to test it:
https://github.com/Patternslib/Patterns/blob/pat-push/src/pat/push/tools/README.md
=> pat-push: New pattern for replacing html content on push events.

src/core/utils.js, src/core/utils.test.js, src/pat/auto-suggest/auto-suggest.js, src/pat/checklist/checklist.js, src/pat/checklist/checklist.test.js, src/pat/depends/depends.js, src/pat/depends/depends.test.js
Use ES6 idoms and simplify codebase as I'm reading the code to understand what's going on.
=> Moderznize and simplify codebase

CHANGES.md, src/pat/scroll/scroll.js
@pilz can you or we together check if that fixes the problem?
I have troubles reproducing the incorrect behavior.
=> pat scroll: Fix scrolling offset incorrectly applied. Fixes: #763.

src/pat/checklist/index.html
Goal: show that it works in general
(Since I have cases in jekyll where this does not work)
=> Update radio example in pat-checklist to load page with one option checked

CHANGES.md, index.html, package.json, src/core/utils.js, src/pat/tabs/tabs.js, src/pat/tabs/tabs.test.js, src/polyfills.js, yarn.lock
http://localhost:4003/library.html needs CSS adaption the navigation tabs to grow even if no more items are added....
=> pat tabs: Refactor based on ResizeObserver and fix problems calculating the with with transitions.

CHANGES.md, src/pat/inject/documentation.md, src/pat/inject/index.html
@cornae I added a demo test case to illustrate the behavior you reported to me.
I can't reproduce it - it seems to work just fine.
Maybe the markup needs to be adapted to illustrate the misbehavior?
I need some more info to create a ticket for the problem.
=> pat-inject: Fix documentation about special target self and demo that behavior

CHANGES.md, src/pat/inject/inject.js, src/pat/inject/inject.test.js
Fixes: https://github.com/quaive/ploneintranet.prototype/issues/1164
=> pat inject: Fix formaction button injections with target self.

CHANGES.md, src/pat/inject/inject.js, src/pat/inject/inject.test.js
pat inject: Make sure that nested pat-inject element have the correct context for target ``self``.
Fixes: https://github.com/quaive/ploneintranet.prototype/issues/1164
=> pat inject: Fix target-self context for nested pat-inject

src/pat/scroll/index.html, src/pat/scroll/scroll.js, src/pat/scroll/scroll.test.js
~~Hold merge; I'm not yet clear on what the issue is (see #842) so I don't know whether this solves it.~~
Closes #842
=> pat-scroll: Allow a delay before scrolling

src/pat/bumper/bumper.js, src/pat/bumper/bumper.test.js, src/pat/bumper/index.html
This is a little lazy - the main class is configurable but the new classes are hard coded.
Refs #847
=> pat-bumper: Extra classes depending on bumped side

src/pat/tabs/tabs.js, src/pat/tabs/tabs.test.js
fix(pat tabs): Improve calculation of available space. It does now 1) check for line breaks of tab elements and 2) check if new position exceeds initial width of .pat-tabs container.
=> improve tabs calculation

src/core/utils.js, src/core/utils.test.js, src/pat/tabs/tabs.js, src/pat/tabs/tabs.test.js
- Stabilizes and optimizes the algorithm for calculating the available space.
- Does not run the algorithm unnecessarily
- Should fix the infinite loop when switching workspaces in Quaive.
=> pat tabs stabilization

.husky/commit-msg, Makefile
I am not sure about this patch, but it seems to work for me.
Fixes #879
=> maint: Fix the pre-commit command

src/core/parser.js, src/core/parser.test.js
fix(pat inject): Parse data attributes as JSON also when the value is a JSON array.
=> fix data attributes JSON parsing

src/pat/colour-picker/_colour-picker.scss, src/pat/date-picker/_date-picker.scss, src/pat/tooltip/_tooltip.scss, style/patterns.css
1) relative paths were not found
2) do not use bare-css imports but include the referenced CSS in the compiled output. See: https://sass-lang.com/documentation/at-rules/import#importing-css
=> Cleanup CSS - Fixes

src/pat/tooltip/index.html, src/pat/tooltip/tooltip.js, src/pat/tooltip/tooltip.test.js
Note: This is a work in progress.
=> [WIP] Changes for integrating tiptap

src/pat/ajax/ajax.js, src/pat/ajax/ajax.test.js, src/pat/inject/inject.js, src/pat/inject/inject.test.js
Atlernative and continuation of: https://github.com/Patternslib/Patterns/pull/894
Related:
https://github.com/quaive/ploneintranet/pull/4439
https://github.com/quaive/quaive.resources.ploneintranet/pull/62
https://github.com/quaive/ploneintranet.prototype/pull/1455
https://github.com/Patternslib/Patterns/pull/913
=> scr-1471: #error_zone error handling

src/core/utils.js, src/core/utils.test.js
feat(core utils): Add escape_html and unescape_html function to repla…ce/unreplace html entity characters.
=> utils: escape/unescape html

jest.config.js, package.json, src/core/utils.js, src/core/utils.test.js, src/pat/gallery/gallery.js, src/pat/gallery/gallery.test.js, src/pat/gallery/index.html, src/pat/navigation/navigation.test.js, src/pat/switch/switch.js, src/pat/switch/switch.test.js, src/pat/validation/validation.js, yarn.lock
- Modernize code for pat-switch and pat-validation.
- Rework pat-validation using standard form validation API.
-
=> pat-validation + modernization

src/pat/push/push.js
If we need to change the specs of this, we can do this just soon.
But we need an intermediate release with this just now.
=> pat-push: Add support for desktop notifications

src/core/push_kit.js, src/pat/push/push.js
together:
https://github.com/quaive/ploneintranet/pull/4773
https://github.com/Patternslib/Patterns/pull/1011
=> [WIP] pat-push - redirect to notification url

src/pat/tooltip/tooltip.js
- Setting the tooltip-container class before async calls.
- Avoid unnecessary repaints by grouping dom manipulations together.
- Merge onMount and onShow into onShow method.
=> fix(pat tooltip): Avoid repositioning of the tooltip arrow.

src/pat/inject/inject.js, src/pat/navigation/navigation.js
=> fix incorrect navigation state after injection happens

src/core/registry.js, src/pat/close-panel/close-panel.js, src/pat/close-panel/close-panel.test.js, src/pat/inject/inject.js, src/pat/modal/modal.js, src/pat/modal/modal.test.js, src/pat/navigation/navigation.test.js, src/pat/notification/notification.js, src/pat/notification/notification.test.js, src/pat/tooltip/tooltip.js, src/pat/tooltip/tooltip.test.js, src/pat/validation/index.html, src/pat/validation/validation.js, src/pat/validation/validation.test.js
See: https://github.com/syslabcom/scrum/issues/613
=> Fix validation

src/core/basepattern.js, src/core/basepattern.md, src/core/basepattern.test.js, src/core/registry.js
=> Pattern base class / backwards compatible approach

src/core/events.js, src/core/events.test.js, src/pat/sortable/index.html, src/pat/sortable/sortable.js, src/pat/sortable/sortable.test.js
Fix sorting behavior on cloned elements, which broke on Patternslib 9.8.0-alpha.0.
=> fix(pat-sortable): Initialize sorting on cloned elements.

src/pat/calendar/calendar.js
=> fix(pat calendar): Do not set a Content-Type header when no body is submitted

src/core/dom.js, src/pat/inject/inject.js, src/pat/scroll/scroll.js
See individual commit messages.
=> Scrolling helpers

src/pat/auto-submit/auto-submit.js, src/pat/auto-submit/auto-submit.test.js, src/pat/auto-suggest/auto-suggest.test.js, src/pat/inject/inject.js, src/pat/inject/inject.test.js
Fix a problem since Patternslib 9.9.6 where pat-inject didn't work together with pat-autosubmit.
=> fix(pat-inject): Fix problem with pat-autosubmit.
